name: stage-test-xpress-api

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop    

jobs:
  build:
    name: Develop_Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      #deploy      
      - uses: CDNievas/heroku-action@v1.0 # This is the action # This is the action
        with:
          heroku_email: ${{secrets.HEROKU_APP_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_APP_KEY}}
          heroku_app_name: ${{secrets.STAGING_APP_NAME}}
          useforce: true,
          branch: develop
         